// Generated by BUCKLESCRIPT VERSION 4.0.8, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function Of_monad(M) {
  var map = function (f, ma) {
    return Curry._2(M[/* bind */1], (function (a) {
                  return Curry._1(M[/* pure */0], Curry._1(f, a));
                }), ma);
  };
  return /* module */[/* map */map];
}

exports.Of_monad = Of_monad;
/* No side effect */
