// Generated by BUCKLESCRIPT VERSION 4.0.8, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");

function Extend(M) {
  var pure = M[0];
  var $great$great$eq = function (m, f) {
    return Curry._2(M[/* bind */1], f, m);
  };
  var join = function (maa) {
    return Curry._2(M[/* bind */1], (function (ma) {
                  return ma;
                }), maa);
  };
  var sequence = function (mas) {
    return List.fold_right((function (ma, ms) {
                  return Curry._2(M[/* bind */1], (function (a) {
                                return Curry._2(M[/* bind */1], (function (s) {
                                              return Curry._1(pure, /* :: */[
                                                          a,
                                                          s
                                                        ]);
                                            }), ms);
                              }), ma);
                }), mas, Curry._1(pure, /* [] */0));
  };
  return /* module */[
          /* pure */pure,
          /* bind */M[1],
          /* >>= */$great$great$eq,
          /* join */join,
          /* sequence */sequence
        ];
}

exports.Extend = Extend;
/* No side effect */
